version: '3'
services:

  redis:
    image: redis
    networks:
      main:
        aliases:
        - redis

  dataservice:
    build: git://github.com/MFranceschi6/BeepBeep-dataservice
    environment:
      - "CHALLENGES_SERVICE=challenges"
      - "OBJECTIVES_SERVICE=training-objectives"
      - "PYTHONUNBUFFERED=true"
    volumes:
      - "dataservicedb:/tmp/"
    #ports:
    # - "5002:5002"
    networks:
      main:
        aliases:
          - dataservice

  challenges:
    build: git://github.com/MFranceschi6/BeepBeep-challenges
    #ports:
    # - "5003:5003"
    environment:
      - "DATA_SERVICE=dataservice"
      - "PYTHONUNBUFFERED=true"
    networks:
      main:
        aliases:
          - challenges
    volumes:
      - "challengesdb:/tmp/"

  statistics:
    build: git://github.com/MFranceschi6/BeepBeep-statistics
    #ports:
    # - "5001:5001"
    environment:
      - "DATA_SERVICE=dataservice"
      - "PYTHONUNBUFFERED=true"
    networks:
      main:
        aliases:
          - statistics

  training-objectives:
    build: git://github.com/MFranceschi6/BeepBeep-training-objectives
    #ports:
    #  - "5004:5004"
    environment:
      - "DATA_SERVICE=dataservice"
      - "PYTHONUNBUFFERED=true"
    networks:
      main:
        aliases:
          - training-objectives
    volumes:
      - "trainingdb:/tmp/"

  apigateway:
    depends_on:
    - redis
    build:
      context: git://github.com/MFranceschi6/BeepBeep-API-gateway.git
    ports:
    - "5000:5000"
    environment:
    - "CHALLENGES_SERVICE=challenges"
    - "OBJECTIVES_SERVICE=training-objectives"
    - "DATA_SERVICE=dataservice"
    - "STATISTICS_SERVICE=statistics"
    - "STRAVA_CLIENT_ID=29639"
    - "STRAVA_CLIENT_SECRET=a80429b277ed2b47a80ba49cb8f32b7decf8cb87"
    - "REDIS=redis"
    - "PYTHONUNBUFFERED=true"
    volumes:
    - "api-gatewaydb:/tmp/"
    networks:
      main:

  emailer:
    build: git://github.com/MFranceschi6/BeepBeep-emailer.git
    depends_on:
    - redis
    networks:
      main:
    environment:
    - "WEBSITE_NAME=ButterBeepBeep"
    - "GROUP_NAME=ButterGroup"
    - "MAIL_GMAIL_USER=beepbeep.buttergroup@gmail.com"
    - "MAIL_GMAIL_PASS=butter_group"
    - "MAIL_REPORT_SUBJECT=Report"
    - "MAIL_MESSAGE_NO_RUN=norun"
    - "REDIS=redis"
    - "DATA_SERVICE=dataservice"
    - "PYTHONUNBUFFERED=true"

  pump:
    build: git://github.com/MFranceschi6/BeepBeep-data-pump.git
    depends_on:
    - redis
    networks:
      main:
    environment:
    - "REDIS=redis"
    - "DATA_SERVICE=dataservice"
    - "PYTHONUNBUFFERED=true"


volumes:
  dataservicedb:
  challengesdb:
  trainingdb:
  api-gatewaydb:

networks:
  main:
